# permissions for end users to edit keycloakusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakuser-editor-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloakusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloakusers/status
  verbs:
  - get
