# permissions for end users to edit keycloaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-editor-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloaks/status
  verbs:
  - get
