# permissions for end users to view keycloakclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakclient-viewer-role
rules:
- apiGroups:
  - keycloak.org
  resources:
  - keycloakclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.org
  resources:
  - keycloakclients/status
  verbs:
  - get
