# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/keycloak.org_keycloakusers.yaml
- bases/keycloak.org_keycloakbackups.yaml
- bases/keycloak.org_keycloakrealms.yaml
- bases/keycloak.org_keycloakclients.yaml
- bases/keycloak.org_keycloaks.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_keycloakusers.yaml
#- patches/webhook_in_keycloakbackups.yaml
#- patches/webhook_in_keycloakrealms.yaml
#- patches/webhook_in_keycloakclients.yaml
#- patches/webhook_in_keycloaks.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_keycloakusers.yaml
#- patches/cainjection_in_keycloakbackups.yaml
#- patches/cainjection_in_keycloakrealms.yaml
#- patches/cainjection_in_keycloakclients.yaml
#- patches/cainjection_in_keycloaks.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
